# Generated by Django 4.1.7 on 2025-10-05 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drill', models.CharField(choices=[('ADD', 'たし算'), ('SUB', 'ひき算'), ('MUL', 'かけ算'), ('DIV', 'わり算')], max_length=3)),
                ('round_index', models.IntegerField()),
                ('score', models.IntegerField()),
                ('total_after_round', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemMistake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drill', models.CharField(choices=[('ADD', 'たし算'), ('SUB', 'ひき算'), ('MUL', 'かけ算'), ('DIV', 'わり算')], max_length=3)),
                ('a', models.IntegerField()),
                ('b', models.IntegerField()),
                ('correct_answer', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistakes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, help_text='返信が必要な場合のみ任意で入力', max_length=254, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='scorehistory',
            index=models.Index(fields=['user', 'drill'], name='crud_scoreh_user_id_053d9e_idx'),
        ),
        migrations.AddIndex(
            model_name='problemmistake',
            index=models.Index(fields=['user', 'drill'], name='crud_proble_user_id_76d2d7_idx'),
        ),
    ]
